// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonUserBase } from "./common-user-base";

/**
 *
 * @export
 * @interface CommentComment
 */
export interface CommentComment {
  /**
   * 文章的id
   * @type {string}
   * @memberof CommentComment
   */
  AHashId?: string;
  /**
   *
   * @type {string}
   * @memberof CommentComment
   */
  CHashId?: string;
  /**
   * 该评论被回复的数量，当为一级评论时候，显示数量，二级的时候，显示为0
   * @type {number}
   * @memberof CommentComment
   */
  ChildNum?: number;
  /**
   * comment
   * @type {string}
   * @memberof CommentComment
   */
  Content?: string;
  /**
   * comment publication date, format mm-dd
   * @type {string}
   * @memberof CommentComment
   */
  CreateDate?: string;
  /**
   * 该评论获得的点赞数量
   * @type {number}
   * @memberof CommentComment
   */
  FavoriteCount?: number;
  /**
   *
   * @type {boolean}
   * @memberof CommentComment
   */
  IsFavorite?: boolean;
  /**
   * 如果该评论为某评论的回复，则该字段为被回复的用户的hashID
   * @type {string}
   * @memberof CommentComment
   */
  RepliedUHashId?: string;
  /**
   * comment user information
   * @type {CommonUserBase}
   * @memberof CommentComment
   */
  User?: CommonUserBase;
}
