// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommonUserProfile
 */
export interface CommonUserProfile {
  /**
   * user avatar URL
   * @type {string}
   * @memberof CommonUserProfile
   */
  avatar?: string;
  /**
   * image at the top of the user\'s personal page
   * @type {string}
   * @memberof CommonUserProfile
   */
  background_image?: string;
  /**
   * user profile
   * @type {string}
   * @memberof CommonUserProfile
   */
  signature?: string;
}
