// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonArticleBasePreload } from "./common-article-base-preload";

/**
 *
 * @export
 * @interface CommonArticleBase
 */
export interface CommonArticleBase {
  /**
   *
   * @type {string}
   * @memberof CommonArticleBase
   */
  content?: string;
  /**
   *
   * @type {CommonArticleBasePreload}
   * @memberof CommonArticleBase
   */
  preload?: CommonArticleBasePreload;
}
