// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommonArticleInfo
 */
export interface CommonArticleInfo {
  /**
   *
   * @type {number}
   * @memberof CommonArticleInfo
   */
  collect_count?: number;
  /**
   * total number of comments on the video
   * @type {number}
   * @memberof CommonArticleInfo
   */
  comment_count?: number;
  /**
   *
   * @type {boolean}
   * @memberof CommonArticleInfo
   */
  is_collect?: boolean;
  /**
   * true-Liked，false-did not like
   * @type {boolean}
   * @memberof CommonArticleInfo
   */
  is_favorite?: boolean;
  /**
   * total number of likes for the video
   * @type {number}
   * @memberof CommonArticleInfo
   */
  like_count?: number;
  /**
   *
   * @type {number}
   * @memberof CommonArticleInfo
   */
  viewed_count?: number;
}
