// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommentCommentActionRequest
 */
export interface CommentCommentActionRequest {
  /**
   * 文章的id
   * @type {string}
   * @memberof CommentCommentActionRequest
   */
  aHashId?: string;
  /**
   * 评论内容
   * @type {string}
   * @memberof CommentCommentActionRequest
   */
  content?: string;
  /**
   * 评论等级，只能为1或者2
   * @type {number}
   * @memberof CommentCommentActionRequest
   */
  degree?: number;
  /**
   * 父亲评论的id
   * @type {string}
   * @memberof CommentCommentActionRequest
   */
  pHashId?: string;
}
