// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FavoriteFavoriteActionRequest
 */
export interface FavoriteFavoriteActionRequest {
  /**
   *
   * @type {string}
   * @memberof FavoriteFavoriteActionRequest
   */
  aHashID?: string;
  /**
   * 1-like, 2-unlike ,3-nor like,nor unlike
   * @type {number}
   * @memberof FavoriteFavoriteActionRequest
   */
  actionType?: number;
  /**
   *
   * @type {string}
   * @memberof FavoriteFavoriteActionRequest
   */
  cHashID?: string;
}
