// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
  /**
   * 上传的文件
   * @type {any}
   * @memberof InlineObject
   */
  file: any;
  /**
   * 上传的类型，是头像还是背景图片
   * @type {string}
   * @memberof InlineObject
   */
  file_type: string;
}
