// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonArticleCard } from "./common-article-card";

/**
 *
 * @export
 * @interface PublishCardsResponse
 */
export interface PublishCardsResponse {
  /**
   *
   * @type {Array<CommonArticleCard>}
   * @memberof PublishCardsResponse
   */
  List?: Array<CommonArticleCard>;
  /**
   *
   * @type {number}
   * @memberof PublishCardsResponse
   */
  status_code?: number;
  /**
   *
   * @type {string}
   * @memberof PublishCardsResponse
   */
  status_msg?: string;
}
