// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonArticle } from "./common-article";

/**
 *
 * @export
 * @interface PublishArticleResponse
 */
export interface PublishArticleResponse {
  /**
   *
   * @type {CommonArticle}
   * @memberof PublishArticleResponse
   */
  article?: CommonArticle;
  /**
   *
   * @type {number}
   * @memberof PublishArticleResponse
   */
  status_code?: number;
  /**
   *
   * @type {string}
   * @memberof PublishArticleResponse
   */
  status_msg?: string;
}
