// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonUser } from "./common-user";

/**
 *
 * @export
 * @interface RelationRelationFollowListResponse
 */
export interface RelationRelationFollowListResponse {
  /**
   *
   * @type {number}
   * @memberof RelationRelationFollowListResponse
   */
  status_code?: number;
  /**
   *
   * @type {string}
   * @memberof RelationRelationFollowListResponse
   */
  status_msg?: string;
  /**
   * User information list
   * @type {Array<CommonUser>}
   * @memberof RelationRelationFollowListResponse
   */
  user_list?: Array<CommonUser>;
}
