// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonUser } from "./common-user";

/**
 *
 * @export
 * @interface UserUserResponse
 */
export interface UserUserResponse {
  /**
   *
   * @type {number}
   * @memberof UserUserResponse
   */
  status_code?: number;
  /**
   *
   * @type {string}
   * @memberof UserUserResponse
   */
  status_msg?: string;
  /**
   * User Info
   * @type {CommonUser}
   * @memberof UserUserResponse
   */
  user?: CommonUser;
}
