// tslint:disable
/**
 * blog_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommonUserProfile } from "./common-user-profile";

/**
 *
 * @export
 * @interface UserUserActionProfileModifyRequest
 */
export interface UserUserActionProfileModifyRequest {
  /**
   *
   * @type {CommonUserProfile}
   * @memberof UserUserActionProfileModifyRequest
   */
  user_profile?: CommonUserProfile;
}
